/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3169XrgUDxh
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex flex-col w-full">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <CalendarDaysIcon className="w-6 h-6" />
            <span className="sr-only">Employee Shift Calendar</span>
          </Link>
        </nav>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-6 md:gap-8 md:p-8">
        <div className="flex justify-between">
          <Button className="w-[240px] justify-start text-left font-normal">
            <ArrowLeftIcon className="mr-1 h-4 w-4 -translate-x-1" />
            Previous Month
          </Button>
          <Button className="w-[240px] justify-start text-left font-normal">
            Next Month
            <ArrowRightIcon className="ml-1 h-4 w-4 -translate-x-1" />
          </Button>
        </div>
        <Card>
          <Popover>
            <PopoverTrigger asChild>
              <Button className="w-[240px] justify-start text-left font-normal" variant="outline">
                <CalendarDaysIcon className="mr-1 h-4 w-4 -translate-x-1" />
                View Shifts
              </Button>
            </PopoverTrigger>
            <PopoverContent align="start" className="w-auto p-0">
              <Calendar initialFocus mode="single" />
            </PopoverContent>
          </Popover>
          <CardContent className="grid grid-cols-7 grid-rows-6 gap-6">
            <div className="text-md font-semibold">Mon</div>
            <div className="text-md font-semibold">Tue</div>
            <div className="text-md font-semibold">Wed</div>
            <div className="text-md font-semibold">Thu</div>
            <div className="text-md font-semibold">Fri</div>
            <div className="text-md font-semibold">Sat</div>
            <div className="text-md font-semibold">Sun</div>
            <div className="border rounded p-4">
              <div className="text-sm font-semibold">1</div>
              <div className="flex justify-between items-center">
                <div>
                  <p className="text-xs">Start: 6:00 AM</p>
                  <p className="text-xs">End: 2:00 PM</p>
                </div>
                <SunIcon className="w-4 h-4" />
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}


function CalendarDaysIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}


function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
